import React from "react";
const base=import.meta.env.BASE_URL;
export default function Slide6(){return <div className="w-screen h-screen overflow-hidden relative bg-[#fbfdff] text-[#111] font-sans">
      <div className="absolute inset-x-0 top-0 h-[15vh] bg-[#f8fbff] border-b-[0.35vh] border-[#d6e4f2]" />
      <div className="absolute left-[3vw] top-[2.5vh] w-[9vw] h-[9vh] rounded-full border-[0.18vw] border-[#0070c0] bg-white flex items-center justify-center font-bold text-[1.5vw] text-[#1f497d] text-center leading-tight">[TEAM<br/>NAME]</div>
      <h1 className="absolute left-[15vw] right-[20vw] top-[4.1vh] text-center font-serif font-bold text-[3vw] leading-none tracking-tight text-[#111]">RESEARCH AND REFERENCES</h1>
      <img src={`${base}sih-2026-logo.png`} crossOrigin="anonymous" alt="Smart India Hackathon 2026 logo" className="absolute right-[2vw] top-[0.4vh] w-[17vw] h-[12vh] object-contain" />
      <div className="absolute inset-x-0 bottom-0 h-[7.4vh] bg-[#0070c0]" />
      <div className="absolute left-[38vw] bottom-[2.15vh] text-white text-[1.5vw] font-medium">@SIH Idea submission- Template</div>
      <div className="absolute right-[2vw] bottom-[2.1vh] text-white/85 text-[1.5vw]">06 / 06</div>
  <div className="absolute left-[4vw] top-[18vh] right-[4vw] grid grid-cols-2 gap-[2.5vw]">
    <div><h2 className="text-[1.6vw] font-black text-[#1f497d] tracking-wider">REGULATORY BASIS</h2><div className="mt-[1.5vh] space-y-[1.4vh] text-[1.6vw]"><div className="border-b border-[#b9cbd9] pb-[1.2vh]"><b>Legal Metrology Act, 2009</b><p className="text-[#4d5c68]">India Code — indiacode.nic.in</p></div><div className="border-b border-[#b9cbd9] pb-[1.2vh]"><b>Legal Metrology (Packaged Commodities) Rules, 2011</b><p className="text-[#4d5c68]">Department of Consumer Affairs — consumeraffairs.nic.in</p></div><div><b>Department advisories and amendments</b><p className="text-[#4d5c68]">Rule changes reviewed before updating the deterministic check set.</p></div></div></div>
    <div><h2 className="text-[1.6vw] font-black text-[#1f497d] tracking-wider">TECHNICAL BASIS</h2><div className="mt-[1.5vh] space-y-[1.4vh] text-[1.6vw]"><div className="border-b border-[#b9cbd9] pb-[1.2vh]"><b>Gemini API documentation</b><p className="text-[#4d5c68]">ai.google.dev — image understanding and structured output</p></div><div className="border-b border-[#b9cbd9] pb-[1.2vh]"><b>OpenAPI Specification</b><p className="text-[#4d5c68]">openapis.org — shared frontend/backend contract</p></div><div><b>Prototype evidence</b><p className="text-[#4d5c68]">Working HYPER LENS scanner, editable extraction, deterministic scoring and report views.</p></div></div></div>
  </div>
  <div className="absolute left-[4vw] top-[52vh] right-[4vw] bg-[#dce6f2] border-[.2vw] border-[#1f497d] p-[1.5vw] grid grid-cols-[1fr_.8fr] gap-[2vw]"><div><h3 className="text-[1.55vw] font-black text-[#1f497d]">VALIDATION PRINCIPLE</h3><p className="mt-[1vh] text-[1.55vw] leading-snug">HYPER LENS does not ask a language model to interpret the law. The model reads visible text; a reviewable rule engine evaluates the declarations.</p></div><img src={`${base}hyper-lens-scanner.jpg`} crossOrigin="anonymous" alt="HYPER LENS package scanner" className="w-full h-[13vh] object-cover object-top border border-[#8aa8c0]" /></div>
  <p className="absolute left-[4vw] bottom-[9.5vh] text-[1.5vw] text-[#5d6872]">Reference links should be checked against the latest official amendment before final portal submission.</p>
</div>}