import React from "react";
const base=import.meta.env.BASE_URL;
export default function Slide4(){return <div className="w-screen h-screen overflow-hidden relative bg-[#fbfdff] text-[#111] font-sans">
      <div className="absolute inset-x-0 top-0 h-[15vh] bg-[#f8fbff] border-b-[0.35vh] border-[#d6e4f2]" />
      <div className="absolute left-[3vw] top-[2.5vh] w-[9vw] h-[9vh] rounded-full border-[0.18vw] border-[#0070c0] bg-white flex items-center justify-center font-bold text-[1.5vw] text-[#1f497d] text-center leading-tight">[TEAM<br/>NAME]</div>
      <h1 className="absolute left-[15vw] right-[20vw] top-[4.1vh] text-center font-serif font-bold text-[3vw] leading-none tracking-tight text-[#111]">FEASIBILITY AND VIABILITY</h1>
      <img src={`${base}sih-2026-logo.png`} crossOrigin="anonymous" alt="Smart India Hackathon 2026 logo" className="absolute right-[2vw] top-[0.4vh] w-[17vw] h-[12vh] object-contain" />
      <div className="absolute inset-x-0 bottom-0 h-[7.4vh] bg-[#0070c0]" />
      <div className="absolute left-[38vw] bottom-[2.15vh] text-white text-[1.5vw] font-medium">@SIH Idea submission- Template</div>
      <div className="absolute right-[2vw] bottom-[2.1vh] text-white/85 text-[1.5vw]">04 / 06</div>
  <div className="absolute left-[4vw] top-[18vh] right-[4vw] grid grid-cols-[1.05fr_.95fr] gap-[2.5vw]">
    <div><h2 className="text-[1.6vw] font-black text-[#1f497d] tracking-wider">WHY IT IS BUILDABLE</h2><div className="mt-[1.5vh] space-y-[1.1vh] text-[1.6vw]"><p className="border-b border-[#bfd0df] pb-[1vh]"><b>Working web prototype</b> — capture, extraction, correction, scoring and reporting are implemented.</p><p className="border-b border-[#bfd0df] pb-[1vh]"><b>Low hardware barrier</b> — runs on a phone or laptop camera; no dedicated scanner is required.</p><p className="border-b border-[#bfd0df] pb-[1vh]"><b>Controlled AI role</b> — visual reading is separated from rule evaluation.</p><p><b>Maintainable rules</b> — checks can be reviewed, versioned and extended without retraining OCR.</p></div></div>
    <div><h2 className="text-[1.6vw] font-black text-[#1f497d] tracking-wider">RISKS AND RESPONSES</h2><div className="mt-[1.5vh] grid grid-cols-[.8fr_1.2fr] text-[1.5vw] border border-[#9fb7cb]"><div className="bg-[#dce6f2] font-bold p-[.85vw]">Blur / glare</div><div className="p-[.85vw]">Confidence flag, recapture guidance, manual correction</div><div className="bg-[#dce6f2] font-bold p-[.85vw]">Rule changes</div><div className="p-[.85vw]">Versioned rule packs and dated report output</div><div className="bg-[#dce6f2] font-bold p-[.85vw]">Model outage</div><div className="p-[.85vw]">Bounded retries, clear failure state, no fabricated extraction</div><div className="bg-[#dce6f2] font-bold p-[.85vw]">False certainty</div><div className="p-[.85vw]">Human verification for low-confidence declarations</div></div></div>
  </div>
  <div className="absolute left-[4vw] top-[56vh] right-[4vw]"><h2 className="text-[1.5vw] font-black text-[#1f497d] tracking-wider">IMPLEMENTATION PATH</h2><div className="mt-[1.2vh] grid grid-cols-4 gap-[.9vw] text-[1.5vw]"><div className="bg-[#eef5fb] border-t-[.6vh] border-[#0070c0] p-[.8vw]"><b>Pilot</b><p>Curated package categories and field checklist</p></div><div className="bg-[#eef5fb] border-t-[.6vh] border-[#0070c0] p-[.8vw]"><b>Validate</b><p>Expert review of findings and edge cases</p></div><div className="bg-[#eef5fb] border-t-[.6vh] border-[#0070c0] p-[.8vw]"><b>Integrate</b><p>Inspection workflow, report export and audit trail</p></div><div className="bg-[#eef5fb] border-t-[.6vh] border-[#0070c0] p-[.8vw]"><b>Scale</b><p>More languages, categories and rule versions</p></div></div></div>
</div>}