import React from "react";
const base=import.meta.env.BASE_URL;
export default function Slide3(){return <div className="w-screen h-screen overflow-hidden relative bg-[#fbfdff] text-[#111] font-sans">
      <div className="absolute inset-x-0 top-0 h-[15vh] bg-[#f8fbff] border-b-[0.35vh] border-[#d6e4f2]" />
      <div className="absolute left-[3vw] top-[2.5vh] w-[9vw] h-[9vh] rounded-full border-[0.18vw] border-[#0070c0] bg-white flex items-center justify-center font-bold text-[1.5vw] text-[#1f497d] text-center leading-tight">[TEAM<br/>NAME]</div>
      <h1 className="absolute left-[15vw] right-[20vw] top-[4.1vh] text-center font-serif font-bold text-[3vw] leading-none tracking-tight text-[#111]">TECHNICAL APPROACH</h1>
      <img src={`${base}sih-2026-logo.png`} crossOrigin="anonymous" alt="Smart India Hackathon 2026 logo" className="absolute right-[2vw] top-[0.4vh] w-[17vw] h-[12vh] object-contain" />
      <div className="absolute inset-x-0 bottom-0 h-[7.4vh] bg-[#0070c0]" />
      <div className="absolute left-[38vw] bottom-[2.15vh] text-white text-[1.5vw] font-medium">@SIH Idea submission- Template</div>
      <div className="absolute right-[2vw] bottom-[2.1vh] text-white/85 text-[1.5vw]">03 / 06</div>
  <div className="absolute left-[3vw] top-[17vh] w-[94vw] h-[45vh]">
    <div className="absolute left-0 top-0 w-[15vw] h-[39vh] bg-[#eef5fb] border-[.18vw] border-[#9ab6cf] p-[1.3vw]"><h3 className="text-[1.5vw] text-[#0070c0] font-black tracking-wider">INPUT LAYER</h3><div className="mt-[3vh] text-[2.4vw] font-black">PACKAGE<br/>IMAGE</div><p className="mt-[2vh] text-[1.5vw] leading-snug">Camera / upload<br/>JPEG · PNG · WebP</p><div className="mt-[3vh] h-[.7vh] bg-[#e52545]" /></div>
    <div className="absolute left-[17vw] top-[7vh] text-[3vw] text-[#0070c0]">→</div>
    <div className="absolute left-[21vw] top-0 w-[22vw] h-[39vh] border-[.2vw] border-[#0070c0] bg-white p-[1.3vw]"><h3 className="text-[1.5vw] text-[#0070c0] font-black tracking-wider">PERCEPTION LAYER</h3><div className="mt-[1.7vh] bg-[#dcebf7] p-[.8vw] text-[1.5vw] font-bold">Gemini Vision OCR</div><div className="mt-[1vh] bg-[#dcebf7] p-[.8vw] text-[1.5vw] font-bold">Text + confidence</div><div className="mt-[1vh] bg-[#dcebf7] p-[.8vw] text-[1.5vw] font-bold">Declaration normalizer</div><p className="mt-[1.5vh] text-[1.5vw]">No compliance verdict is generated here.</p></div>
    <div className="absolute left-[45vw] top-[7vh] text-[3vw] text-[#0070c0]">→</div>
    <div className="absolute left-[49vw] top-0 w-[22vw] h-[39vh] border-[.2vw] border-[#77933c] bg-white p-[1.3vw]"><h3 className="text-[1.5vw] text-[#4f6d22] font-black tracking-wider">DECISION LAYER</h3><div className="mt-[1.7vh] bg-[#eaf1df] p-[.8vw] text-[1.5vw] font-bold">Editable declarations</div><div className="mt-[1vh] bg-[#eaf1df] p-[.8vw] text-[1.5vw] font-bold">Deterministic checks</div><div className="mt-[1vh] bg-[#eaf1df] p-[.8vw] text-[1.5vw] font-bold">Weighted score engine</div><p className="mt-[1.5vh] text-[1.5vw]">Same input produces the same result.</p></div>
    <div className="absolute left-[73vw] top-[7vh] text-[3vw] text-[#0070c0]">→</div>
    <div className="absolute right-0 top-0 w-[22vw] h-[39vh] bg-[#1f497d] text-white p-[1.3vw]"><h3 className="text-[1.5vw] text-[#b9d7f0] font-black tracking-wider">EVIDENCE LAYER</h3><div className="mt-[1.7vh] border border-white/50 p-[.8vw] text-[1.5vw] font-bold">Field-level status</div><div className="mt-[1vh] border border-white/50 p-[.8vw] text-[1.5vw] font-bold">Reason + recommendation</div><div className="mt-[1vh] border border-white/50 p-[.8vw] text-[1.5vw] font-bold">Inspection report</div><p className="mt-[1.5vh] text-[1.5vw]">Traceable from output back to source text.</p></div>
    <div className="absolute left-[21vw] top-[41.5vh] w-[50vw] h-[4vh] bg-[#eef2f5] border border-[#aab8c4] flex items-center justify-center text-[1.5vw] font-bold tracking-wide">React + TypeScript · Express API · Shared OpenAPI contract · Secure server-side API key</div>
  </div>
  <div className="absolute left-[4vw] top-[63vh] right-[4vw] flex justify-between text-[1.5vw]"><p><b>Quality control:</b> confidence threshold + manual correction</p><p><b>Failure handling:</b> validation, bounded retries, explicit errors</p><p><b>Scale path:</b> stateless API + versioned rule packs</p></div>
</div>}