import React from "react";
const base=import.meta.env.BASE_URL;
export default function Slide5(){return <div className="w-screen h-screen overflow-hidden relative bg-[#fbfdff] text-[#111] font-sans">
      <div className="absolute inset-x-0 top-0 h-[15vh] bg-[#f8fbff] border-b-[0.35vh] border-[#d6e4f2]" />
      <div className="absolute left-[3vw] top-[2.5vh] w-[9vw] h-[9vh] rounded-full border-[0.18vw] border-[#0070c0] bg-white flex items-center justify-center font-bold text-[1.5vw] text-[#1f497d] text-center leading-tight">[TEAM<br/>NAME]</div>
      <h1 className="absolute left-[15vw] right-[20vw] top-[4.1vh] text-center font-serif font-bold text-[3vw] leading-none tracking-tight text-[#111]">IMPACT AND BENEFITS</h1>
      <img src={`${base}sih-2026-logo.png`} crossOrigin="anonymous" alt="Smart India Hackathon 2026 logo" className="absolute right-[2vw] top-[0.4vh] w-[17vw] h-[12vh] object-contain" />
      <div className="absolute inset-x-0 bottom-0 h-[7.4vh] bg-[#0070c0]" />
      <div className="absolute left-[38vw] bottom-[2.15vh] text-white text-[1.5vw] font-medium">@SIH Idea submission- Template</div>
      <div className="absolute right-[2vw] bottom-[2.1vh] text-white/85 text-[1.5vw]">05 / 06</div>
  <div className="absolute left-[4vw] top-[18vh] right-[4vw] grid grid-cols-[.95fr_1.05fr] gap-[3vw]">
    <div className="relative h-[43vh]"><div className="absolute left-[14vw] top-[13vh] w-[14vw] h-[14vw] rounded-full bg-[#1f497d] text-white flex items-center justify-center text-center text-[1.65vw] font-black p-[2vw]">TRUSTED PACKAGE DECLARATIONS</div><div className="absolute left-0 top-0 w-[13vw] h-[13vw] rounded-full bg-[#dce6f2] border-[.25vw] border-[#0070c0] flex items-center justify-center text-center text-[1.5vw] font-bold p-[1.4vw]">Consumers<br/><span className="font-normal">clearer information</span></div><div className="absolute right-0 top-0 w-[13vw] h-[13vw] rounded-full bg-[#eaf1df] border-[.25vw] border-[#77933c] flex items-center justify-center text-center text-[1.5vw] font-bold p-[1.4vw]">Manufacturers<br/><span className="font-normal">early correction</span></div><div className="absolute left-0 bottom-0 w-[13vw] h-[13vw] rounded-full bg-[#f7e5e3] border-[.25vw] border-[#c0504d] flex items-center justify-center text-center text-[1.5vw] font-bold p-[1.4vw]">Inspectors<br/><span className="font-normal">structured evidence</span></div><div className="absolute right-0 bottom-0 w-[13vw] h-[13vw] rounded-full bg-[#eee8f5] border-[.25vw] border-[#8064a2] flex items-center justify-center text-center text-[1.5vw] font-bold p-[1.4vw]">Retailers<br/><span className="font-normal">faster screening</span></div></div>
    <div><h2 className="text-[1.5vw] font-black text-[#1f497d] tracking-wider">OUTCOMES</h2><div className="mt-[1.6vh] space-y-[1.3vh]"><div className="border-t-[.7vh] border-[#0070c0] bg-[#eef5fb] p-[1vw]"><b className="text-[1.5vw]">Social</b><p className="text-[1.55vw]">Makes package information easier to verify and explain.</p></div><div className="border-t-[.7vh] border-[#77933c] bg-[#f1f5ea] p-[1vw]"><b className="text-[1.5vw]">Operational</b><p className="text-[1.55vw]">Turns repetitive visual checks into a consistent digital workflow.</p></div><div className="border-t-[.7vh] border-[#c0504d] bg-[#f8eceb] p-[1vw]"><b className="text-[1.5vw]">Economic</b><p className="text-[1.55vw]">Helps identify declaration issues before printing or distribution.</p></div><div className="border-t-[.7vh] border-[#8064a2] bg-[#f1edf6] p-[1vw]"><b className="text-[1.5vw]">Governance</b><p className="text-[1.55vw]">Produces a reviewable trail from source image to final finding.</p></div></div></div>
  </div>
  <p className="absolute left-[4vw] bottom-[9.5vh] text-[1.5vw] font-bold text-[#1f497d]">Designed as decision support: the evidence stays visible and the inspector remains in control.</p>
</div>}